have_fun: false

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: true
    summary: true
    code_review: true
    include_drafts: false

ignore_patterns:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "coverage/**"
  - ".serena/**"
  - "**/*.lock"
  - "package-lock.json"
  - "**/*.log"
  - ".git/**"
  - ".github/workflows/**"
